PortAudio: com.portaudio.PlaySine Class Reference
com.portaudio.PlaySine Class Reference
Public Member Functions
void play ()
Static Public Member Functions
static void main (String[] args)
Detailed Description
Definition at line 11 of file PlaySine.java.
Member Function Documentation
void com.portaudio.PlaySine.play () inline
Create a stream on the default device then play sine waves.
Definition at line 45 of file PlaySine.java.
References com.portaudio.BlockingStream.close(), com.portaudio.PortAudio.initialize(), com.portaudio.BlockingStream.start(), com.portaudio.BlockingStream.stop(), and com.portaudio.PortAudio.terminate().
The documentation for this class was generated from the following file:
PlaySine.java